[package]
name = "time"
description = "Simple count CLI run time."
version = "0.1.0"
edition = "2021"

[[bin]]
name = "demo"
path = "src/demo.rs"

[dependencies]
clap = { version = "4.5.32", features = ["derive"] }
colored = "3.0.0"
